"""Generate the compliance and classification dashboard.

The script reads only outputs/compliance_report.json and derives every table,
card, chart, and interpretation from that report.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import html
import json
from pathlib import Path
import re
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT = REPO_ROOT / "outputs" / "compliance_report.json"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "dashboard.html"
FRONTIER_TRADE_IDS = {"T026", "T027", "T028", "T033"}

STATUS_COLORS = {
    "COMPLIANT": "#2f7d4f",
    "NONCOMPLIANT": "#b83232",
    "CONDITIONAL": "#b7791f",
    "NOT_APPLICABLE": "#586174",
}

STATUS_LABEL_COLORS = {
    "COMPLIANT": "#e7f5ec",
    "NONCOMPLIANT": "#fde8e8",
    "CONDITIONAL": "#fff4d6",
    "NOT_APPLICABLE": "#edf0f5",
}

STATUS_ORDER = ["COMPLIANT", "NONCOMPLIANT", "CONDITIONAL", "NOT_APPLICABLE", "UNKNOWN"]


def load_report(path: Path) -> list[dict[str, Any]]:
    """Load the compliance report generated by run_compliance_check.py."""

    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON array")
    return data


def regimes_in_report(rows: list[dict[str, Any]]) -> list[str]:
    """Return regime names in first-seen order."""

    regimes: list[str] = []
    for row in rows:
        for regime in row.get("regime_results", {}):
            if regime not in regimes:
                regimes.append(regime)
    return regimes


def status_badge(status: str) -> str:
    """Render a compact status badge."""

    bg = STATUS_LABEL_COLORS.get(status, "#f1f5f9")
    fg = STATUS_COLORS.get(status, "#1f2937")
    return (
        f'<span class="status-badge" style="background:{bg};color:{fg};">'
        f"{html.escape(status)}</span>"
    )


def frontier_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Return the four trades used for the Part 4 classification frontier."""

    return [row for row in rows if row.get("trade_id") in FRONTIER_TRADE_IDS]


def money_label(row: dict[str, Any]) -> str:
    """Format notional amount and currency from classified fields."""

    fields = row.get("classified_fields", {})
    amount = fields.get("notional_amount")
    currency = fields.get("notional_currency") or ""
    if isinstance(amount, (int, float)):
        return f"{amount:,.0f} {currency}".strip()
    return html.escape(str(amount or "N/A"))


def compact_list(items: list[str], limit: int = 8) -> str:
    """Format a compact comma-separated list with an overflow marker."""

    visible = items[:limit]
    text = ", ".join(visible)
    if len(items) > limit:
        text += f" +{len(items) - limit} more"
    return text


def render_part4_overview(rows: list[dict[str, Any]], regimes: list[str]) -> str:
    """Render headline metrics for the event-contract frontier."""

    frontier = frontier_rows(rows)
    status_counts = Counter(
        result.get("status", "UNKNOWN")
        for row in rows
        for result in row.get("regime_results", {}).values()
    )
    source_counts = Counter(row.get("source") or "unknown" for row in rows)
    no_taxonomy = sum(
        row.get("classification_flag") == "NOVEL_INSTRUMENT_NO_TAXONOMY"
        for row in frontier
    )
    cftc_conditional = sum(
        row.get("regime_results", {}).get("CFTC", {}).get("status") == "CONDITIONAL"
        for row in frontier
    )
    emir_outside = sum(
        row.get("regime_results", {}).get("EMIR", {}).get("status") == "NOT_APPLICABLE"
        for row in frontier
    )

    metrics = [
        ("Trades Analysed", len(rows), "All loaded from the JSON report"),
        ("Regime Decisions", sum(status_counts.values()), ", ".join(regimes)),
        ("Frontier Trades", len(frontier), "T026-T028 and T033"),
        ("No DSB Taxonomy", no_taxonomy, "No matched UPI template"),
        ("Conditional CFTC", cftc_conditional, "Event-contract classification boundary"),
        ("Outside EMIR", emir_outside, "Not treated as EMIR OTC derivatives here"),
    ]
    cards = "".join(
        f"""
        <div class="metric-card">
          <span>{html.escape(label)}</span>
          <strong>{value}</strong>
          <small>{html.escape(note)}</small>
        </div>
        """
        for label, value, note in metrics
    )

    return f"""
    <section class="frontier-overview">
      <div class="section-kicker">Event-Contract Focus</div>
      <h2>Classification Frontier for Event Contracts</h2>
      <p>
        This dashboard separates ordinary reporting errors from the harder
        classification question: whether prediction and event contracts fit existing OTC
        derivative reporting taxonomies. The four highlighted trades are analysed
        directly from {html.escape(', '.join(regimes))} results in the JSON report.
        Source mix: {html.escape(', '.join(f'{k}: {v}' for k, v in source_counts.items()))}.
      </p>
      <div class="metric-grid">{cards}</div>
    </section>
    """


def render_heatmap(rows: list[dict[str, Any]], regimes: list[str]) -> str:
    """Render portfolio compliance status by trade and regime."""

    body_rows = []
    for row in rows:
        row_class = ' class="frontier-row"' if row.get("trade_id") in FRONTIER_TRADE_IDS else ""
        cells = [
            f"<th>{html.escape(row['trade_id'])}</th>",
            f"<td>{html.escape(row.get('asset_class') or '')}</td>",
        ]
        for regime in regimes:
            result = row.get("regime_results", {}).get(regime, {})
            status = result.get("status", "UNKNOWN")
            color = STATUS_COLORS.get(status, "#64748b")
            cells.append(
                f'<td class="heat-cell" style="background:{color};">'
                f"{html.escape(status)}</td>"
            )
        body_rows.append(f"<tr{row_class}>{''.join(cells)}</tr>")

    regime_headers = "".join(f"<th>{html.escape(regime)}</th>" for regime in regimes)
    legend = "".join(
        f"""
        <span class="legend-item">
          <i style="background:{STATUS_COLORS.get(status, '#64748b')}"></i>
          {html.escape(status)}
        </span>
        """
        for status in STATUS_ORDER
        if any(
            result.get("status", "UNKNOWN") == status
            for row in rows
            for result in row.get("regime_results", {}).values()
        )
    )
    return f"""
    <section>
      <h2>Portfolio Compliance Heatmap</h2>
      <div class="legend">{legend}</div>
      <div class="scroll-table">
        <table class="heatmap">
          <thead>
            <tr><th>Trade</th><th>Asset Class</th>{regime_headers}</tr>
          </thead>
          <tbody>
            {''.join(body_rows)}
          </tbody>
        </table>
      </div>
    </section>
    """


def collect_messages(row: dict[str, Any]) -> list[str]:
    """Collect all errors and warnings attached to one report row."""

    messages: list[str] = []
    messages.extend(row.get("parse_errors", []))
    messages.extend(row.get("upi_errors", []))
    messages.extend(row.get("upi_warnings", []))
    for result in row.get("regime_results", {}).values():
        messages.extend(result.get("errors", []))
        messages.extend(result.get("warnings", []))
    return [message for message in messages if message]


def extract_field_name(message: str) -> str:
    """Extract a stable field-like label from an error or warning message."""

    patterns = [
        r"missing(?: EMIR)? required field: ([A-Za-z0-9_]+)",
        r"([A-Za-z0-9_]+)=.* is not in codeset",
        r"([A-Za-z0-9_]+) failed ISO",
        r"([A-Za-z0-9_]+) must ",
        r"([A-Za-z0-9_]+) is missing",
    ]
    for pattern in patterns:
        match = re.search(pattern, message)
        if match:
            return match.group(1)

    lowered = message.lower()
    if "uti namespace" in lowered or "uti suffix" in lowered:
        return "uti"
    if "libor" in lowered:
        return "reference_rate"
    if "parse issue" in lowered or "timestamp" in lowered:
        return "execution_timestamp"
    return "other"


def render_error_frequency(rows: list[dict[str, Any]]) -> str:
    """Render horizontal bars for the most common failing fields."""

    counts = Counter()
    affected_trades: dict[str, set[str]] = defaultdict(set)
    for row in rows:
        for message in collect_messages(row):
            field = extract_field_name(message)
            counts[field] += 1
            affected_trades[field].add(row.get("trade_id", "UNKNOWN"))

    if not counts:
        return "<section><h2>Error Frequency</h2><p>No errors or warnings found.</p></section>"

    max_count = max(counts.values())
    bars = []
    for field, count in counts.most_common(12):
        width = max(6, round((count / max_count) * 100))
        bars.append(
            f"""
            <div class="bar-row">
              <div class="bar-label">{html.escape(field)}</div>
              <div class="bar-track">
                <div class="bar-fill" style="width:{width}%"></div>
              </div>
              <div class="bar-value">{count}</div>
              <div class="bar-trades">Affected trades: {html.escape(compact_list(sorted(affected_trades[field]), 10))}</div>
            </div>
            """
        )

    return f"""
    <section>
      <h2>Error Frequency</h2>
      <div class="bar-chart">{''.join(bars)}</div>
    </section>
    """


def compliance_rate(status_counts: Counter[str]) -> float:
    """Return compliant trades divided by all status-bearing trades."""

    total = sum(status_counts.values())
    if total == 0:
        return 0.0
    return status_counts.get("COMPLIANT", 0) / total


def render_asset_breakdown(rows: list[dict[str, Any]], regimes: list[str]) -> str:
    """Render status mix by asset class and regime."""

    grouped: dict[str, dict[str, Counter[str]]] = defaultdict(lambda: defaultdict(Counter))
    for row in rows:
        asset_class = row.get("asset_class") or "Unknown"
        for regime in regimes:
            status = row.get("regime_results", {}).get(regime, {}).get("status", "UNKNOWN")
            grouped[asset_class][regime][status] += 1

    body_rows = []
    for asset_class in sorted(grouped):
        cells = [f"<th>{html.escape(asset_class)}</th>"]
        for regime in regimes:
            counts = grouped[asset_class][regime]
            total = sum(counts.values())
            rate = round(compliance_rate(counts) * 100)
            counts_text = ", ".join(
                f"{status}: {counts[status]}"
                for status in STATUS_ORDER
                if counts.get(status)
            )
            segments = "".join(
                f"""
                <span
                  style="width:{(counts[status] / total) * 100 if total else 0:.2f}%;
                         background:{STATUS_COLORS.get(status, '#64748b')};"
                  title="{html.escape(status)}: {counts[status]}"
                ></span>
                """
                for status in STATUS_ORDER
                if counts.get(status)
            )
            cells.append(
                f"""
                <td>
                  <div class="asset-cell">
                    <div class="stack-track">{segments}</div>
                    <strong>{rate}% compliant</strong>
                    <small>{html.escape(counts_text)}</small>
                  </div>
                </td>
                """
            )
        body_rows.append(f"<tr>{''.join(cells)}</tr>")

    headers = "".join(f"<th>{html.escape(regime)}</th>" for regime in regimes)
    return f"""
    <section>
      <h2>Asset Class Breakdown</h2>
      <table>
        <thead><tr><th>Asset Class</th>{headers}</tr></thead>
        <tbody>{''.join(body_rows)}</tbody>
      </table>
    </section>
    """


def render_frontier_panel(rows: list[dict[str, Any]], regimes: list[str]) -> str:
    """Render prominent Part 4 cards for event-contract frontier trades."""

    cards = []
    for row in frontier_rows(rows):
        fields = row.get("classified_fields", {})
        statuses = []
        rationale = []
        for regime in regimes:
            result = row.get("regime_results", {}).get(regime, {})
            statuses.append(
                f"""
                <div class="regime-pill">
                  <span>{html.escape(regime)}</span>
                  {status_badge(result.get('status', 'UNKNOWN'))}
                </div>
                """
            )
            rationale.append(
                f"""
                <li>
                  <strong>{html.escape(regime)}</strong>:
                  {html.escape(' '.join(result.get('notes', [])) or 'No regime note supplied.')}
                </li>
                """
            )

        note_text = row.get("classification_note") or "No classification note supplied."

        cards.append(
            f"""
            <article class="frontier-card">
              <div class="frontier-card-head">
                <div>
                  <h3>{html.escape(row.get('trade_id', ''))}</h3>
                  <p>{html.escape(row.get('use_case') or 'Unknown use case')}</p>
                </div>
                <span class="source-tag">{html.escape(row.get('source') or 'report')}</span>
              </div>
              <dl class="frontier-fields">
                <div><dt>Platform</dt><dd>{html.escape(fields.get('platform') or 'N/A')}</dd></div>
                <div><dt>Platform Type</dt><dd>{html.escape(fields.get('platform_type') or 'N/A')}</dd></div>
                <div><dt>Notional</dt><dd>{money_label(row)}</dd></div>
                <div><dt>UPI Template</dt><dd>{html.escape(row.get('matched_template') or 'No product definition')}</dd></div>
                <div><dt>Classification Flag</dt><dd>{html.escape(row.get('classification_flag') or 'N/A')}</dd></div>
                <div><dt>UPI Status</dt><dd>{html.escape(row.get('upi_status') or 'N/A')}</dd></div>
              </dl>
              <div class="regime-row">{''.join(statuses)}</div>
              <p class="frontier-note">{html.escape(note_text)}</p>
              <ul class="rationale-list">{''.join(rationale)}</ul>
            </article>
            """
        )

    return f"""
    <section class="frontier-section">
      <h2>Classification Frontier Panel</h2>
      <div class="frontier-grid">{''.join(cards)}</div>
    </section>
    """


def render_interpretation(rows: list[dict[str, Any]]) -> str:
    """Render the required written interpretation paragraphs."""

    regimes = regimes_in_report(rows)
    status_counts = Counter(
        result.get("status", "UNKNOWN")
        for row in rows
        for result in row.get("regime_results", {}).values()
    )
    noncompliant_trades = sorted(
        {
            row["trade_id"]
            for row in rows
            for result in row.get("regime_results", {}).values()
            if result.get("status") == "NONCOMPLIANT"
        }
    )
    message_counts = Counter()
    for row in rows:
        for message in collect_messages(row):
            message_counts[extract_field_name(message)] += 1

    event_trades = [row["trade_id"] for row in frontier_rows(rows)]
    event_statuses = Counter(
        result.get("status", "UNKNOWN")
        for row in rows
        if row.get("trade_id") in FRONTIER_TRADE_IDS
        for result in row.get("regime_results", {}).values()
    )
    fully_compliant_controls = [
        row["trade_id"]
        for row in rows
        if row.get("source") == "additional"
        and all(
            row.get("regime_results", {}).get(regime, {}).get("status") == "COMPLIANT"
            for regime in regimes
        )
    ]
    designed_exceptions = [
        row["trade_id"]
        for row in rows
        if row.get("source") == "additional"
        and any(
            row.get("regime_results", {}).get(regime, {}).get("status")
            in {"NONCOMPLIANT", "CONDITIONAL", "NOT_APPLICABLE"}
            for regime in regimes
        )
    ]

    top_fields = ", ".join(
        f"{field} ({count})" for field, count in message_counts.most_common(4)
    )
    noncompliant_preview = ", ".join(noncompliant_trades[:18])
    if len(noncompliant_trades) > 18:
        noncompliant_preview += " and others"
    event_status_text = ", ".join(
        f"{status}: {count}" for status, count in event_statuses.items()
    )
    compliant_count = status_counts.get("COMPLIANT", 0)
    noncompliant_count = status_counts.get("NONCOMPLIANT", 0)
    conditional_count = status_counts.get("CONDITIONAL", 0)
    not_applicable_count = status_counts.get("NOT_APPLICABLE", 0)
    frontier_platforms = ", ".join(
        sorted(
            {
                row.get("classified_fields", {}).get("platform")
                for row in frontier_rows(rows)
                if row.get("classified_fields", {}).get("platform")
            }
        )
    )
    frontier_use_cases = ", ".join(
        f"{row.get('trade_id')} ({row.get('use_case')})"
        for row in frontier_rows(rows)
    )
    asset_counts = Counter(row.get("asset_class") or "Unknown" for row in rows)
    asset_mix = ", ".join(
        f"{asset}: {count}" for asset, count in asset_counts.most_common()
    )

    return f"""
    <section class="interpretation">
      <h2>Interpretation</h2>
      <p>
        The dashboard is generated from a single source file,
        <strong>outputs/compliance_report.json</strong>, which contains {len(rows)}
        trades and {sum(status_counts.values())} regime-level decisions across
        {html.escape(', '.join(regimes))}. The portfolio heatmap shows a strongly
        exception-heavy reporting book: {noncompliant_count} regime outcomes are
        non-compliant, compared with {compliant_count} compliant outcomes,
        {conditional_count} conditional outcomes, and {not_applicable_count}
        not-applicable outcomes. This matters because the failures are not confined
        to one isolated trade; non-compliant trades include
        {html.escape(noncompliant_preview)}, indicating a portfolio-level control
        problem rather than a single booking mistake.
      </p>
      <p>
        The error-frequency chart narrows the operational problem to repeatable
        data-quality checks. The most frequent message groups are
        {html.escape(top_fields or 'none')}. These are exactly the types of fields
        that a pre-submission validation layer should catch: counterparty LEI
        format and checksum controls, mandatory collateral and margin fields, UTI
        consistency, and reference-rate hygiene. In other words, the dashboard does
        not merely count failed trades; it points to the specific controls that
        would reduce the greatest number of reporting breaks.
      </p>
      <p>
        The asset-class breakdown gives useful context for the classification question.
        The source data covers {html.escape(asset_mix)}, so the event-contract
        trades are being compared against a mixed OTC derivative portfolio rather
        than viewed in isolation. Conventional asset classes mainly fail because
        required reporting fields or identifiers are invalid. By contrast, the
        event-contract records fail to map into an ANNA-DSB UPI product definition,
        which makes their issue a classification boundary problem rather than an
        ordinary completeness problem. The classification frontier panel therefore
        deserves separate treatment: the highlighted trades are
        {html.escape(frontier_use_cases)}, executed on
        {html.escape(frontier_platforms or 'the reported event-contract platforms')}.
        The regime outcome count is {html.escape(event_status_text)}. Kalshi-style
        regulated event contracts are treated as conditional under the CFTC logic,
        while Polymarket/offshore or EMIR-facing event contracts are outside the
        reporting chain used in this project. The additional test set still includes
        clean controls ({html.escape(', '.join(fully_compliant_controls) or 'none')})
        and designed data exceptions
        ({html.escape(', '.join(designed_exceptions) or 'none')}), so the dashboard
        separates three concepts that should not be mixed: valid trades, data
        reporting failures, and true taxonomy gaps.
      </p>
    </section>
    """


def render_dashboard(rows: list[dict[str, Any]], source_path: Path) -> str:
    """Render the complete dashboard HTML document."""

    regimes = regimes_in_report(rows)
    status_counts = Counter(
        result.get("status", "UNKNOWN")
        for row in rows
        for result in row.get("regime_results", {}).values()
    )
    try:
        source_label = html.escape(str(source_path.relative_to(REPO_ROOT)))
    except ValueError:
        source_label = html.escape(str(source_path))

    summary_items = "".join(
        f"<li><strong>{html.escape(status)}</strong><span>{count}</span></li>"
        for status, count in status_counts.items()
    )

    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>MH6822 Compliance Dashboard</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #172026;
      --muted: #607080;
      --line: #d6dde3;
      --panel: #f4f7f8;
      --accent: #0f766e;
      --amber: #b7791f;
      --rose: #b83232;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      color: var(--ink);
      background: #f6f8f8;
      font-family: Arial, Helvetica, sans-serif;
      line-height: 1.45;
    }}
    header {{
      padding: 30px 32px 20px;
      border-bottom: 1px solid var(--line);
      background: #ffffff;
    }}
    main {{ padding: 24px 32px 40px; }}
    h1 {{ margin: 0 0 8px; font-size: 30px; }}
    h2 {{ margin: 0 0 14px; font-size: 20px; }}
    p {{ max-width: 980px; margin: 0 0 14px; }}
    section {{
      margin: 0 0 28px;
      padding: 20px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fff;
    }}
    .eyebrow {{
      margin-bottom: 8px;
      color: var(--accent);
      font-size: 13px;
      font-weight: 700;
      text-transform: uppercase;
    }}
    .source {{ color: var(--muted); font-size: 14px; }}
    .summary {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      gap: 12px;
      list-style: none;
      padding: 0;
      margin: 20px 0 0;
    }}
    .summary li {{
      display: flex;
      justify-content: space-between;
      gap: 12px;
      padding: 12px 14px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fff;
    }}
    .frontier-overview {{
      border-color: #9cc9c3;
      background: #eef7f5;
    }}
    .section-kicker {{
      color: var(--accent);
      font-size: 12px;
      font-weight: 700;
      text-transform: uppercase;
      margin-bottom: 6px;
    }}
    .metric-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
      gap: 12px;
      margin-top: 18px;
    }}
    .metric-card {{
      display: grid;
      gap: 4px;
      padding: 14px 16px;
      border: 1px solid #b9d8d3;
      border-radius: 8px;
      background: #fff;
    }}
    .metric-card span {{ color: var(--muted); font-weight: 700; }}
    .metric-card strong {{ font-size: 30px; line-height: 1; }}
    .scroll-table {{ overflow-x: auto; }}
    table {{ width: 100%; border-collapse: collapse; font-size: 14px; }}
    th, td {{ padding: 9px 10px; border-bottom: 1px solid var(--line); text-align: left; vertical-align: top; }}
    thead th {{ background: var(--panel); }}
    .heatmap th:first-child {{ position: sticky; left: 0; background: #fff; }}
    .frontier-row th:first-child,
    .frontier-row td {{
      box-shadow: inset 0 0 0 999px rgba(15, 118, 110, 0.07);
    }}
    .heat-cell {{ color: #fff; font-weight: 700; text-align: center; min-width: 132px; }}
    .status-badge {{ display: inline-block; border-radius: 999px; padding: 3px 9px; font-size: 12px; font-weight: 700; }}
    .legend {{
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
      margin-bottom: 12px;
    }}
    .legend-item {{
      display: inline-flex;
      align-items: center;
      gap: 6px;
      color: var(--muted);
      font-size: 12px;
      font-weight: 700;
    }}
    .legend-item i {{
      display: inline-block;
      width: 12px;
      height: 12px;
      border-radius: 3px;
    }}
    .bar-chart {{ display: grid; gap: 10px; }}
    .bar-row {{ display: grid; grid-template-columns: minmax(150px, 220px) 1fr 44px; gap: 12px; align-items: center; }}
    .bar-label {{ font-weight: 700; }}
    .bar-track, .rate-track {{ height: 14px; background: #e5edf7; border-radius: 999px; overflow: hidden; }}
    .bar-fill {{ height: 100%; background: var(--accent); }}
    .bar-value {{ text-align: right; font-weight: 700; }}
    .bar-trades {{
      grid-column: 2 / 4;
      color: var(--muted);
      font-size: 12px;
    }}
    .rate-cell {{ display: grid; gap: 6px; min-width: 160px; }}
    .rate-fill {{ height: 100%; background: #2f7d4f; }}
    .asset-cell {{ display: grid; gap: 6px; min-width: 190px; }}
    .stack-track {{
      display: flex;
      height: 16px;
      overflow: hidden;
      border-radius: 999px;
      background: #e5edf7;
    }}
    .stack-track span {{ display: block; min-width: 2px; }}
    .frontier-grid {{
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 14px;
    }}
    .frontier-card {{
      padding: 16px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fbfcfd;
    }}
    .frontier-card-head {{
      display: flex;
      justify-content: space-between;
      gap: 12px;
      align-items: flex-start;
      margin-bottom: 12px;
    }}
    .frontier-card h3 {{ margin: 0; font-size: 22px; }}
    .frontier-card p {{ margin: 2px 0 0; }}
    .source-tag {{
      padding: 3px 8px;
      border-radius: 999px;
      background: #e7eef2;
      color: var(--muted);
      font-size: 12px;
      font-weight: 700;
    }}
    .frontier-fields {{
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 10px;
      margin: 0 0 14px;
    }}
    .frontier-fields div {{
      padding: 9px 10px;
      border: 1px solid #e1e7eb;
      border-radius: 6px;
      background: #fff;
    }}
    dt {{ color: var(--muted); font-size: 12px; font-weight: 700; }}
    dd {{ margin: 2px 0 0; overflow-wrap: anywhere; }}
    .regime-row {{
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin-bottom: 10px;
    }}
    .regime-pill {{
      display: flex;
      gap: 7px;
      align-items: center;
      padding: 5px 8px;
      border: 1px solid #dde4e9;
      border-radius: 999px;
      background: #fff;
      font-size: 12px;
      font-weight: 700;
    }}
    .frontier-note {{
      color: #344450;
      font-size: 13px;
    }}
    .rationale-list {{
      display: grid;
      gap: 7px;
      margin: 10px 0 0;
      padding-left: 18px;
      color: #344450;
      font-size: 13px;
    }}
    .interpretation {{
      border-left: 4px solid var(--accent);
    }}
    small {{ color: var(--muted); }}
    @media (max-width: 720px) {{
      header, main {{ padding-left: 16px; padding-right: 16px; }}
      .bar-row {{ grid-template-columns: 1fr; gap: 4px; }}
      .bar-trades {{ grid-column: 1; }}
      .bar-value {{ text-align: left; }}
      .frontier-fields {{ grid-template-columns: 1fr; }}
    }}
  </style>
</head>
<body>
  <header>
    <div class="eyebrow">MH6822 Homework 2</div>
    <h1>Compliance and Classification Dashboard</h1>
    <div class="source">Only data source: {source_label}</div>
    <ul class="summary">{summary_items}</ul>
  </header>
  <main>
    {render_part4_overview(rows, regimes)}
    {render_frontier_panel(rows, regimes)}
    {render_heatmap(rows, regimes)}
    {render_error_frequency(rows)}
    {render_asset_breakdown(rows, regimes)}
    {render_interpretation(rows)}
  </main>
</body>
</html>
"""


def parse_args() -> argparse.Namespace:
    """Parse dashboard generation arguments."""

    parser = argparse.ArgumentParser(description="Generate the compliance dashboard HTML.")
    parser.add_argument(
        "--input",
        default=str(DEFAULT_REPORT),
        help="Path to the compliance_report.json file.",
    )
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Path for the generated dashboard HTML.",
    )
    return parser.parse_args()


def main() -> None:
    """Generate the dashboard file."""

    args = parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)
    rows = load_report(input_path)
    html_text = render_dashboard(rows, input_path)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_text, encoding="utf-8")
    print(f"Wrote dashboard for {len(rows)} trades to {output_path}")


if __name__ == "__main__":
    main()
